### ISSUE TITLE
location of conda

### ISSUE THREAD

**Issue by guyskk** [opticspy/lightpipes#19]
Does this the correct location in your system? @FredvanGoor 
```
from getpass import getuser

CONDA_32 = r'C:\Users\{}\Miniconda32\Scripts\conda.exe'.format(getuser())
CONDA_64 = r'C:\Users\{}\Miniconda64\Scripts\conda.exe'.format(getuser())
```
I expect `getuser()` return `Fred` in your system and `kk` in my system, so we needn't modify it any more.

**Comment by FredvanGoor** [comment]
Yes, that works on my PC as well.
