### ISSUE TITLE
Unclear documentation of argument nsteps in Steps()

### ISSUE THREAD

**Issue by MaxGilljohann** [opticspy/lightpipes#26]
Hi there, 

the command reference of Steps(z, nstep, refr, Fin) says

> Propagates the field a distance, z, in nstep steps in a medium [...]

and to me that is a bit confusing. I would expect that the distance z is divided into n steps, but apparently the Field seems to be propagated n times the distance z through the medium.

Anyhow, thanks a lot for the development and the python port of lightpipes, it helps me a lot!

Best regards,
Max

**Comment by FredvanGoor** [comment]
Hi Max,

I changed the description  of the Steps command.
Thank you for the comment.

Fred.

**Comment by MaxGilljohann** [comment]
Hi Fred,

thank you!

Best regards,
Max
