### ISSUE TITLE
Installation of lightpipes package

### ISSUE THREAD

**Issue by yellow-force** [opticspy/lightpipes#35]
Dear authors/contributors,

Thank you for developing this LightPipes package. I found it really useful when simulating diffraction optics.

I have a few questions regarding installing the Python version of the package:

1, I found that there are two branches: master and PyLightPipes. I guess the first one is written in C while the later one is in pure Python (please correct me if I am wrong). If I am right, is the pure Python version complete (i.e. is it ready to use or still need further development before I can use)?

2. If the Python version is ready to use, how should I install it? Previously I have tried to use "pip install LightPipes" but it seemed only install the master branch? From https://pypi.org/project/LightPipes/ I found that the last release was Oct 2019, which is same as the last update of the master branch. So if I use pip install lightpipes I will then be installing the master branch, not the pure Python version?

Many thanks in advance for the clarification!

**Comment by FredvanGoor** [comment]
Indeed, the PyLightpipes version is under development to be a “pure Python”
version. It is not yet ready.
If you do pip install lightpipes the c++ version, in the master branch will
be installed.
If you cannot wait you have to clone from the PyLightpipes branch.

Fred

Op ma 20 apr. 2020 om 06:00 schreef yellow-force <notifications@github.com>
