### ISSUE TITLE
choose an open source license

### ISSUE THREAD

**Issue by guyskk** [opticspy/lightpipes#4]
like this: https://github.com/numpy/numpy/blob/master/LICENSE.txt

**Comment by FredvanGoor** [comment]
I have copy-paste the numpy license and modified it to LightPipes. Have a look.

**Comment by guyskk** [comment]
:+1:

**Comment by guyskk** [comment]
Origin LICENSE of LightPipes is MIT, see https://github.com/opticspy/lightpipes/blob/fe42713453b951623252bcdfd4e52fcaa45f2261/LightPipes-Packages/sources/setup.py#L64 , but LICENSE.txt is BSD-3-clause which is the same as numpy.
Should I change the license in setup.py or LICENSE.txt? MIT or BSD?

**Comment by FredvanGoor** [comment]
I am not familiar with licenses but I think that BSD is appropriate because there is binary code involved.  People can use and distribute but should mention the copyright in their release. Making money with LightPipes by others is not a problem for me.

**Comment by guyskk** [comment]
#18
