### ISSUE TITLE
Why LightPipes should be put in try finally block?

### ISSUE THREAD

**Issue by guyskk** [opticspy/lightpipes#6]
I found this in examples:
```python
try:
	LP=LightPipes.Init()
        ...
finally:
	del LightPipes
```

**Comment by FredvanGoor** [comment]
It can be removed. I thought it was nice to clean up at the end. But it is done automatically at the end? Then I will remove it

**Comment by guyskk** [comment]
python has garbage collection which will clean up automatically.

**Comment by guyskk** [comment]
Also, the `try import except` can be replaced by  single import.
