### ISSUE TITLE
build wheels for windows use docker

### ISSUE THREAD

**Issue by guyskk** [opticspy/lightpipes#7]
thanks to: https://github.com/dockcross/dockcross
it's possible to use image `dockcross/windows-x64` and `dockcross/windows-x86` to build wheels for windows.
Is it a good idea?

**Comment by FredvanGoor** [comment]
Yes I think so. I will try it. I can produce wheels for python 3.5 but not for puthon 2.7 The problem is that the fftw3-3.dll is not included in the 2.7 wheel and not installed in the 2.7 site_packages directory. Any idea what is happening with?
The 3.5 wheel works fine with the current setup.py

**Comment by guyskk** [comment]
https://github.com/dockcross/dockcross/issues/19
https://packaging.python.org/appveyor/
https://github.com/numpy/windows-wheel-builder

**Comment by guyskk** [comment]
use miniconda instead
